### ISSUE TITLE
Write helpful README files

### ISSUE THREAD

**Issue by bgotink** [bgotink/ngx-playwright#1]

**Comment by rafagsiqueira** [comment]
@bgotink I am having a lot of issues with the "stabilization" of the environment. Forcing me to manually add loops like this one:
```
let icon: MatIconHarness | null = null;
  while (!icon) {
    icon = await loader.getHarnessOrNull(MatIconHarness.with({name: 'create_new_folder'}));
    await page.waitForTimeout(50);
  }
```
on multiple parts of my tests. Whenever trying to use the forceStabilize or waitForAngular functions, my tests just freeze. 
Is there a way I can leverage the automaticStabilization features?
