### ISSUE TITLE
Tests for Angular Library

### ISSUE THREAD

**Issue by russelporosky** [bgotink/ngx-playwright#19]
Running `ng add @ngx-playwright/test` requires an Application Project to be defined. Library projects will have components that require testing as well, but the schematic can't be used on library projects right now.

**Comment by bgotink** [comment]
Hmm yeah I wrote the schematic under the assumption that libraries don't have a `serve` target&hellip;
I've updated the schematic to test for a `serve` target instead, could you try again with version 0.5.4?

**Comment by bgotink** [comment]
I'm going to close this issue, feel free to comment if that's in correct or open new issues if you run into other problems!
