### ISSUE TITLE
Exit code 0 despite failing tests

### ISSUE THREAD

**Issue by xxluke** [bgotink/ngx-playwright#21]
Hi, 

I tested the `@ngx-playwright/test` (0.5.8) library and noticed that even when the tests fail, the `ng e2e --ui=false` command terminates with exit code 0, which stands for a success. This is an issue because a CI pipeline wouldn't know that something went wrong.

When I call the "original" `playwright test` instead, it correctly ends with an exit code of 1.

```
1 failed
    [setup] › setup\auth.setup.ts:16:6 › authenticate ──────────────────────────────────────────────
7 did not run

Process finished with exit code 0
```
angular.json:
```
        "e2e": {
          "builder": "@ngx-playwright/test:run",
          "options": {
            "devServerTarget": "my-app:serve",
            "ui": true
          }
        }
```

**Comment by bgotink** [comment]
Yeah I'd noticed something weird with exit codes. In our case CI still properly fails once it processes the junit report generated by playwright, so I hadn't given this priority.

**Comment by xxluke** [comment]
Thank you for the quick response, it works as expected now.
